name: Production Build
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
        
    - name: Install modules
      run: npm install --prefix "./src/server/"

    - name: Runs test
      run: npm test --prefix "./src/server/"

    - name: Build typescript
      run: npm run build:prod --prefix "./src/server/"

    - name: Copy settings
      run: |
        cp ./src/server/creds.json.default ./src/server/dist/creds.json
        cp ./src/server/pow_creds.json.default ./src/server/dist/pow_creds.json
        cp ./src/server/settings.json.default ./src/server/dist/settings.json
        cp ./src/server/token_settings.json.default ./src/server/dist/token_settings.json
        cp ./src/server/user_settings.json.default ./src/server/dist/user_settings.json
        cp ./src/server/package.json ./src/server/dist/package.json
        
    - name: Zip Folder
      run: cd ./src/server/ && zip -r ../../proxy.zip ./dist -x ./dist/__test__\* && cd -

    - name: Release Drafter
      id: release_drafter
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Release Asset
      id: upload_release_asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release_drafter.outputs.upload_url }} # This pulls ID from the Release Drafter step
        asset_path: ./proxy.zip
        asset_name: proxy.zip
        asset_content_type: application/zip
