name: Release Dist Folder
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
        
    - name: Install modules
      run: npm install --prefix "./src/server/"
        
    - name: Build typescript
      run: npm run build --prefix "./src/server/"
        
    - name: Zip Folder
      run: cd src/server/dist/ && zip -r ../../../proxy.zip . -x ./__test__\* && cd -
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: proxy.zip
