name: Code Test
on: 
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
        
    - name: Install modules
      run: npm install --prefix "./src/server/"

    - name: Runs test
      run: npm test --prefix "./src/server/"

    - name: Build typescript
      run: npm run build --prefix "./src/server/"

    - name: Copy settings
      run: |
        cp ./src/server/creds.json.default ./src/server/dist/creds.json
        cp ./src/server/pow_creds.json.default ./src/server/dist/pow_creds.json
        cp ./src/server/settings.json.default ./src/server/dist/settings.json
        cp ./src/server/token_settings.json.default ./src/server/dist/token_settings.json
        cp ./src/server/user_settings.json.default ./src/server/dist/user_settings.json
        cp ./src/server/package.json ./src/server/dist/package.json
        
    - name: Zip Folder
      run: cd ./src/server/ && zip -r ../../proxy.zip ./dist -x ./dist/__test__\* && cd -

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: proxy.zip